import type { BudgetSummary, Category, Transaction, User } from "./types";

/**
 * Sample dataset lifted from the Sprout prototype (user "Sam"). Used to hydrate
 * the client store so the app runs with `npm run dev` before Neon is wired up,
 * and mirrored by `src/db/seed.ts` when seeding a real database.
 */

export const mockUser: User = {
  id: "u_sam",
  name: "Sam Rivera",
  greetingName: "Sam",
  email: "sam@sprout.app",
  currency: "USD",
  budgetCycle: "monthly",
};

export const mockCategories: Category[] = [
  {
    id: "c_bills",
    name: "Bills & rent",
    emoji: "🏠",
    color: "#d97a54",
    monthlyBudgetCents: 100000,
    spentCents: 96000,
  },
  {
    id: "c_groceries",
    name: "Groceries",
    emoji: "🍎",
    color: "#c98a5a",
    monthlyBudgetCents: 60000,
    spentCents: 52000,
  },
  {
    id: "c_shopping",
    name: "Shopping",
    emoji: "🛍️",
    color: "#c25b3a",
    monthlyBudgetCents: 31000,
    spentCents: 31000,
  },
  {
    id: "c_dining",
    name: "Dining out",
    emoji: "🍽️",
    color: "#7e9b6b",
    monthlyBudgetCents: 30000,
    spentCents: 28000,
  },
  {
    id: "c_fun",
    name: "Fun",
    emoji: "🎉",
    color: "#e7a34a",
    monthlyBudgetCents: 22000,
    spentCents: 19000,
  },
  {
    id: "c_transport",
    name: "Transport",
    emoji: "🚗",
    color: "#7e9b6b",
    monthlyBudgetCents: 20000,
    spentCents: 14000,
  },
];

export const mockTransactions: Transaction[] = [
  {
    id: "t_wf",
    merchant: "Whole Foods",
    emoji: "🍎",
    categoryId: "c_groceries",
    categoryName: "Groceries",
    amountCents: -6420,
    method: "card",
    status: "posted",
    dateLabel: "Today",
    occurredAt: "2026-06-18T14:02:00Z",
  },
  {
    id: "t_bb",
    merchant: "Blue Bottle",
    emoji: "🍽️",
    categoryId: "c_dining",
    categoryName: "Dining",
    amountCents: -650,
    method: "card",
    status: "posted",
    dateLabel: "Today",
    occurredAt: "2026-06-18T09:15:00Z",
  },
  {
    id: "t_sp",
    merchant: "Spotify",
    emoji: "🎵",
    categoryId: "c_fun",
    categoryName: "Subscription",
    amountCents: -1199,
    method: "card",
    status: "posted",
    dateLabel: "Today",
    occurredAt: "2026-06-18T06:00:00Z",
  },
  {
    id: "t_ub",
    merchant: "Uber",
    emoji: "🚗",
    categoryId: "c_transport",
    categoryName: "Transport",
    amountCents: -1840,
    method: "card",
    status: "posted",
    dateLabel: "Yesterday",
    occurredAt: "2026-06-17T19:40:00Z",
  },
  {
    id: "t_za",
    merchant: "Zara",
    emoji: "🛍️",
    categoryId: "c_shopping",
    categoryName: "Shopping",
    amountCents: -7900,
    method: "card",
    status: "posted",
    dateLabel: "Yesterday",
    occurredAt: "2026-06-17T13:20:00Z",
  },
  {
    id: "t_sa",
    merchant: "Salary",
    emoji: "💰",
    categoryId: null,
    categoryName: "Income",
    amountCents: 320000,
    method: "transfer",
    status: "posted",
    dateLabel: "Yesterday",
    occurredAt: "2026-06-17T08:00:00Z",
  },
  {
    id: "t_tj",
    merchant: "Trader Joe's",
    emoji: "🍎",
    categoryId: "c_groceries",
    categoryName: "Groceries",
    amountCents: -4210,
    method: "card",
    status: "posted",
    dateLabel: "Jun 12",
    occurredAt: "2026-06-12T17:30:00Z",
  },
  {
    id: "t_su",
    merchant: "Sushi Nozomi",
    emoji: "🍽️",
    categoryId: "c_dining",
    categoryName: "Dining",
    amountCents: -8800,
    method: "card",
    status: "posted",
    dateLabel: "Jun 11",
    occurredAt: "2026-06-11T20:10:00Z",
  },
  {
    id: "t_am",
    merchant: "Amazon",
    emoji: "🛍️",
    categoryId: "c_shopping",
    categoryName: "Shopping",
    amountCents: -13200,
    method: "card",
    status: "posted",
    dateLabel: "Jun 10",
    occurredAt: "2026-06-10T11:05:00Z",
  },
];

/** Headline figures from the prototype's Home hero. */
export const mockSummary: BudgetSummary = {
  safeToSpendCents: 248000,
  spentCents: 324000,
  budgetCents: 400000,
  daysLeft: 6,
};
